In [1]:
from mxnet import nd

/Users/macbook/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL


In [2]:
w = nd.arange(4).reshape((1,1,2,2))
b = nd.array([1])
data = nd.arange(9).reshape((1,1,3,3))
out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[1])
print('input:', data, '\n\n weight:', w, '\n\n bias:', b, '\n\n output:', out)

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]]]
<NDArray 1x1x3x3 @cpu(0)> 

 weight: 
[[[[ 0.  1.]
   [ 2.  3.]]]]
<NDArray 1x1x2x2 @cpu(0)> 

 bias: 
[ 1.]
<NDArray 1 @cpu(0)> 

 output: 
[[[[ 20.  26.]
   [ 38.  44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [3]:
out = nd.Convolution(data, w, b, kernel=w.shape[2:],num_filter=w.shape[1], stride=(2,2), pad=(1,1))
print('input:', data, '\n\n weight:', w, '\n\n bias:', b, '\n\n output:', out)

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]]]
<NDArray 1x1x3x3 @cpu(0)> 

 weight: 
[[[[ 0.  1.]
   [ 2.  3.]]]]
<NDArray 1x1x2x2 @cpu(0)> 

 bias: 
[ 1.]
<NDArray 1 @cpu(0)> 

 output: 
[[[[  1.   9.]
   [ 22.  44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [4]:
w.shape

(1, 1, 2, 2)

In [6]:
w.shape[2:]

(2, 2)

In [8]:
w.shape[1]

1

In [11]:
w = nd.arange(8).reshape((1,2,2,2))
b = nd.array([1])
data = nd.arange(18).reshape((1,2,3,3))
out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[0])
print('input:', data, '\n\n weight:', w, '\n\n bias:', b, '\n\n output:', out)

input: 
[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

 weight: 
[[[[ 0.  1.]
   [ 2.  3.]]

  [[ 4.  5.]
   [ 6.  7.]]]]
<NDArray 1x2x2x2 @cpu(0)> 

 bias: 
[ 1.]
<NDArray 1 @cpu(0)> 

 output: 
[[[[ 269.  297.]
   [ 353.  381.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [12]:
w = nd.arange(16).reshape((2,2,2,2))
data = nd.arange(18).reshape((1,2,3,3))
b = nd.array([1,2])

out = nd.Convolution(data, w, b, kernel=w.shape[2:], num_filter=w.shape[0])

print('input:', data, '\n\nweight:', w, '\n\nbias:', b, '\n\noutput:', out)


input: 
[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

weight: 
[[[[  0.   1.]
   [  2.   3.]]

  [[  4.   5.]
   [  6.   7.]]]


 [[[  8.   9.]
   [ 10.  11.]]

  [[ 12.  13.]
   [ 14.  15.]]]]
<NDArray 2x2x2x2 @cpu(0)> 

bias: 
[ 1.  2.]
<NDArray 2 @cpu(0)> 

output: 
[[[[  269.   297.]
   [  353.   381.]]

  [[  686.   778.]
   [  962.  1054.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [13]:
data = nd.arange(18).reshape((1,2,3,3))

max_pool = nd.Pooling(data=data, pool_type="max", kernel=(2,2))
avg_pool = nd.Pooling(data=data, pool_type="avg", kernel=(2,2))

print('data:', data, '\n\nmax pooling:', max_pool, '\n\navg pooling:', avg_pool)


data: 
[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

max pooling: 
[[[[  4.   5.]
   [  7.   8.]]

  [[ 13.  14.]
   [ 16.  17.]]]]
<NDArray 1x2x2x2 @cpu(0)> 

avg pooling: 
[[[[  2.   3.]
   [  5.   6.]]

  [[ 11.  12.]
   [ 14.  15.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [15]:
import sys
sys.path.append('..')
from utils import load_data_fashion_mnist

In [16]:
batch_size = 256
train_data, test_data = load_data_fashion_mnist(batch_size)

In [17]:
import mxnet as mx

try:
    ctx = mx.gpu()
    _ = nd.zeros((1,), ctx=ctx)
except:
    ctx = mx.cpu()
ctx

cpu(0)

In [18]:
weight_scale = .01
W1 = nd.random_normal(shape=(20,1,5,5), scale=weight_scale, ctx=ctx)
b1 = nd.zeros(W1.shape[0], ctx=ctx)

W2 = nd.random_normal(shape=(50,20,3,3), scale=weight_scale, ctx=ctx)
b2 = nd.zeros(W2.shape[0], ctx=ctx)

W3 = nd.random_normal(shape=(1250,128), scale=weight_scale, ctx=ctx)
b3 = nd.zeros(W3.shape[1], ctx=ctx)

W4 = nd.random_normal(shape=(W3.shape[1],10), scale=weight_scale, ctx=ctx)
b4 = nd.zeros(W4.shape[1], ctx=ctx)

params = [W1, b1, W2, b2, W3, b3, W4, b4]
for param in params:
    param.attach_grad()




In [21]:
def net(X, verbose=False):
    X = X.as_in_context(W1.context)
    # first conv
    h1_conv = nd.Convolution(
        data = X, weight=W1, bias=b1, kernel=W1.shape[2:], num_filter=W1.shape[0])
    h1_activation = nd.relu(h1_conv)
    h1 = nd.Pooling(
        data = h1_activation, pool_type='max', kernel=(2,2), stride=(2,2))
    # second conv
    h2_conv = nd.Convolution(
        data = h1, weight=W2, bias=b2, kernel=W2.shape[2:], num_filter=W2.shape[0])
    h2_activation = nd.relu(h2_conv)
    h2 = nd.Pooling(
        data = h2_activation, pool_type='max', kernel=(2,2), stride=(2,2))
    h2 = nd.flatten(h2)
    # first dense
    h3_linear = nd.dot(h2, W3) + b3
    h3 = nd.relu(h3_linear)
    # second dense
    h4_linear = nd.dot(h3, W4) + b4
    if verbose:
        print('1st conv block:', h1.shape)
        print('2nd conv block:', h2.shape)
        print('1st dense:', h3.shape)
        print('2nd dense:', h4_linear.shape)
        print('output:', h4_linear)
    return h4_linear


In [22]:
for data, _ in train_data:
    net(data, verbose=True)
    break

1st conv block: (256, 20, 12, 12)
2nd conv block: (256, 1250)
1st dense: (256, 128)
2nd dense: (256, 10)
output: 
[[  1.47865467e-06  -2.81311441e-05  -5.06756151e-05 ...,   5.70762677e-05
   -8.42777154e-05   1.18620104e-04]
 [  6.79374352e-07   9.45711417e-06  -1.47839291e-05 ...,   4.50750558e-05
   -7.05736384e-05  -8.06472781e-06]
 [ -2.89115542e-05  -6.41923689e-05  -4.00484641e-05 ...,   7.97795728e-05
   -3.52358693e-05  -1.31978359e-05]
 ..., 
 [ -4.08909909e-06  -4.77952271e-05  -7.70536062e-05 ...,   6.44869069e-05
   -7.85614757e-05   1.46877923e-04]
 [ -6.58104473e-05  -9.54745246e-06  -2.26690936e-05 ...,   7.21471806e-05
   -3.71760871e-05   8.06900280e-05]
 [ -6.51315349e-05  -6.66000560e-05  -4.94176784e-05 ...,   9.92949281e-05
   -4.79809896e-05   6.53801180e-05]]
<NDArray 256x10 @cpu(0)>


In [23]:
from mxnet import autograd as autograd
from utils import SGD, accuracy, evaluate_accuracy
from mxnet import gluon

In [24]:
softmax_cross_entropy = gluon.loss.SoftmaxCrossEntropyLoss()

learning_rate = .2


In [25]:
for epoch in range(5):
    train_loss = 0.
    train_acc = 0.
    for data, label in train_data:
        label = label.as_in_context(ctx)
        with autograd.record():
            output = net(data)
            loss = softmax_cross_entropy(output, label)
        loss.backward()
        SGD(params, learning_rate/batch_size)

        train_loss += nd.mean(loss).asscalar()
        train_acc += accuracy(output, label)

    test_acc = evaluate_accuracy(test_data, net, ctx)
    print("Epoch %d. Loss: %f, Train acc %f, Test acc %f" % (
        epoch, train_loss/len(train_data),
        train_acc/len(train_data), test_acc))


Epoch 0. Loss: 2.302429, Train acc 0.099860, Test acc 0.099960
Epoch 1. Loss: 1.485964, Train acc 0.435513, Test acc 0.686298
Epoch 2. Loss: 0.666411, Train acc 0.742872, Test acc 0.795272
Epoch 3. Loss: 0.518422, Train acc 0.805355, Test acc 0.779948
Epoch 4. Loss: 0.450925, Train acc 0.832365, Test acc 0.831030


卷积神经网络 — 使用Gluon

In [26]:
from mxnet.gluon import nn

In [27]:
net = nn.Sequential()
with net.name_scope():
    net.add(
        nn.Conv2D(channels=20, kernel_size=5, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        nn.Conv2D(channels=50, kernel_size=3, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        nn.Flatten(),
        nn.Dense(128, activation='relu'),
        nn.Dense(10)
    )
    

In [28]:

from mxnet import gluon
import sys
sys.path.append('..')
import utils

# 初始化
ctx = utils.try_gpu()
net.initialize(ctx=ctx)
print('initialize weight on', ctx)

# 获取数据
batch_size = 256
train_data, test_data = utils.load_data_fashion_mnist(batch_size)

# 训练
loss = gluon.loss.SoftmaxCrossEntropyLoss()
trainer = gluon.Trainer(net.collect_params(),
                        'sgd', {'learning_rate': 0.5})
utils.train(train_data, test_data, net, loss,
            trainer, ctx, num_epochs=5)


initialize weight on cpu(0)
Start training on  cpu(0)
Epoch 0. Loss: 1.085, Train acc 0.59, Test acc 0.79, Time 43.2 sec
Epoch 1. Loss: 0.484, Train acc 0.82, Test acc 0.86, Time 42.4 sec
Epoch 2. Loss: 0.390, Train acc 0.86, Test acc 0.85, Time 41.2 sec
Epoch 3. Loss: 0.348, Train acc 0.87, Test acc 0.87, Time 41.1 sec
Epoch 4. Loss: 0.325, Train acc 0.88, Test acc 0.88, Time 41.3 sec
